{{- range $rulesIndex, $ingressRule := $.Values.ingress.rules }}
{{- if eq $rulesIndex 0 }}
{{- $tlsSecretName := "" }}
{{- if $.Values.ingress.tls }}
{{- if not (eq (printf "%s" $.Values.ingress.tls) (printf "%s" false)) }}
  {{- if eq (printf "%s" $.Values.ingress.tls) (printf "%s" true) }}
  {{- if $.Values.ingress.name }}
    {{- $tlsSecretName = (printf "tls-%s" $.Values.ingress.name) }}
  {{- else }}
  {{- if $.Values.service.name }}
    {{- $tlsSecretName = (printf "tls-%s" $.Values.service.name) }}
  {{- else }}
    {{- $tlsSecretName = (printf "tls-%s" $.Release.Name) }}
  {{- end }}
  {{- end }}
  {{- else }}
    {{- $tlsSecretName = $.Values.ingress.tls }}
  {{- end }}
{{- end }}
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if $.Values.ingress.name }}
  name: {{ $.Values.ingress.name | quote }}
  {{- else }}
  {{- if $.Values.ingress.serviceName }}
  name: {{ $.Values.ingress.serviceName | quote }}
  {{- else }}
  {{- if $.Values.service.name }}
  name: {{ $.Values.service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.ingress.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- $addIssuer := true }}
    {{- $addIssuerGroup := true }}
    {{- $addIssuerKind := true }}
    {{- $addClusterIssuer := true }}
    {{- $addIngressClass := true }}
    {{- range $annotationName, $annotationValue := $.Values.ingress.annotations }}
    {{- if or (eq $annotationName "cert-manager.io/issuer") (eq $annotationName "certmanager.k8s.io/issuer") }}
      {{- $addIssuer = false }}
      {{- $addClusterIssuer = false }}
    {{- end }}
    {{- if or (eq $annotationName "cert-manager.io/issuer-group") (eq $annotationName "certmanager.k8s.io/issuer-group") }}
      {{- $addIssuerGroup = false }}
      {{- $addClusterIssuer = false }}
    {{- end }}
    {{- if or (eq $annotationName "cert-manager.io/issuer-kind") (eq $annotationName "certmanager.k8s.io/issuer-kind") }}
      {{- $addIssuerKind = false }}
      {{- $addClusterIssuer = false }}
    {{- end }}
    {{- if or (eq $annotationName "cert-manager.io/cluster-issuer") (eq $annotationName "certmanager.k8s.io/cluster-issuer") }}
      {{- $addIssuer = false }}
      {{- $addIssuerGroup = false }}
      {{- $addIssuerKind = false }}
      {{- $addClusterIssuer = false }}
    {{- end }}
    {{- if or (eq $annotationName "acme.cert-manager.io/http01-ingress-class") (eq $annotationName "certmanager.k8s.io/http01-ingress-class") }}
      {{- $addIngressClass = false }}
    {{- end }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
    {{- if ne (printf "%s" $tlsSecretName) "" }}
    {{- if and $addIssuer $.Values.ingress.tlsIssuer }}
    cert-manager.io/issuer: {{ $.Values.ingress.tlsIssuer | quote }}
    certmanager.k8s.io/issuer: {{ $.Values.ingress.tlsIssuer | quote }}
    {{- if and $addIssuerGroup $.Values.ingress.tlsIssuerGroup }}
    cert-manager.io/issuer-group: {{ $.Values.ingress.tlsIssuerGroup | quote }}
    certmanager.k8s.io/issuer-group: {{ $.Values.ingress.tlsIssuerGroup | quote }}
    {{- end }}
    {{- if and $addIssuerKind $.Values.ingress.tlsIssuerKind }}
    cert-manager.io/issuer-kind: {{ $.Values.ingress.tlsIssuerKind | quote }}
    certmanager.k8s.io/issuer-kind: {{ $.Values.ingress.tlsIssuerKind | quote }}
    {{- end }}
    {{- else if $addClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.tlsClusterIssuer | default "lets-encrypt-http-issuer" | quote }}
    certmanager.k8s.io/cluster-issuer: {{ $.Values.ingress.tlsClusterIssuer | default "lets-encrypt-http-issuer" | quote }}
    {{- end }}
    {{- if $addIngressClass }}
    acme.cert-manager.io/http01-ingress-class: {{ $.Values.ingress.ingressClass | default "nginx" | quote }}
    certmanager.k8s.io/http01-ingress-class: {{ $.Values.ingress.ingressClass | default "nginx" | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if $.Values.ingress.defaultBackend }}
  defaultBackend:
{{ toYaml $.Values.ingress.defaultBackend | indent 4 }}
  {{- end }}
  {{- if $.Values.ingress.ingressClass }}
  ingressClassName: {{ $.Values.ingress.ingressClass }}
  {{- end }}
  rules:
  {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}
  - host: {{ $ingressRule.host | quote }}
    http:
      paths:
      - backend:
          {{- if $ingressRule.serviceName }}
          serviceName: {{ $ingressRule.serviceName | quote }}
          {{- else }}
          {{- if $.Values.service.name }}
          serviceName: {{ $.Values.service.name | quote }}
          {{- else }}
          serviceName: {{ $.Release.Name | quote }}
          {{- end }}
          {{- end }}
          {{- if $ingressRule.servicePort }}
          servicePort: {{ $ingressRule.servicePort }}
          {{- else }}
          servicePort: {{ (index $.Values.service.ports 0).port }}
          {{- end }}
        {{- if $ingressRule.path }}
        path: {{ $ingressRule.path | quote }}
        {{- else }}
        path: /
        {{- end }}
  {{- end }}
  {{- if ne (printf "%s" $tlsSecretName) "" }}
  tls:
  - hosts:
    {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}
    - {{ $ingressRule.host | quote }}
    {{- end }}
    secretName: {{ $tlsSecretName | quote }}
  {{- end }}

---

{{- end }}
{{- end }}
