{{- range $rulesIndex, $ingressRule := $.Values.ingress.rules }}
{{- if eq $rulesIndex 0 }}
{{- $tlsSecretName := "" }}
{{- if $.Values.ingress.tls }}
{{- if not (eq (printf "%s" $.Values.ingress.tls) (printf "%s" false)) }}
  {{- if eq (printf "%s" $.Values.ingress.tls) (printf "%s" true) }}
  {{- if $.Values.ingress.name }}
    {{- $tlsSecretName = (printf "tls-%s" $.Values.ingress.name) }}
  {{- else }}
  {{- if $.Values.service.name }}
    {{- $tlsSecretName = (printf "tls-%s" $.Values.service.name) }}
  {{- else }}
    {{- $tlsSecretName = (printf "tls-%s" $.Release.Name) }}
  {{- end }}
  {{- end }}
  {{- else }}
    {{- $tlsSecretName = $.Values.ingress.tls }}
  {{- end }}
{{- end }}
{{- end }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- if $.Values.ingress.name }}
  name: {{ $.Values.ingress.name | quote }}
  {{- else }}
  {{- if $.Values.ingress.serviceName }}
  name: {{ $.Values.ingress.serviceName | quote }}
  {{- else }}
  {{- if $.Values.service.name }}
  name: {{ $.Values.service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.ingress.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- $addClusterIssuer := true }}
    {{- $addIngressClass := true }}
    {{- range $annotationName, $annotationValue := $.Values.ingress.annotations }}
    {{- if or (eq $annotationName "cert-manager.io/cluster-issuer") (eq $annotationName "certmanager.k8s.io/cluster-issuer") (eq $annotationName "cert-manager.io/issuer") (eq $annotationName "certmanager.k8s.io/issuer") }}
      {{- $addClusterIssuer = false }}
    {{- end }}
    {{- if or (eq $annotationName "acme.cert-manager.io/http01-ingress-class") (eq $annotationName "certmanager.k8s.io/http01-ingress-class") }}
      {{- $addIngressClass = false }}
    {{- end }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
    {{- if ne (printf "%s" $tlsSecretName) "" }}
    {{- if $addClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.tlsClusterIssuer | default "lets-encrypt-http-issuer" | quote }}
    certmanager.k8s.io/cluster-issuer: {{ $.Values.ingress.tlsClusterIssuer | default "lets-encrypt-http-issuer" | quote }}
    {{- end }}
    {{- if $addIngressClass }}
    acme.cert-manager.io/http01-ingress-class: {{ $.Values.ingress.ingressClass | default "nginx" | quote }}
    certmanager.k8s.io/http01-ingress-class: {{ $.Values.ingress.ingressClass | default "nginx" | quote }}
    {{- end }}
    {{- end }}
spec:
  {{- if $.Values.ingress.defaultBackend }}
  defaultBackend:
{{ toYaml $.Values.ingress.defaultBackend | indent 4 }}
  {{- end }}
  {{- if $.Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}

  {{- $svcPort := 0 }}
  {{- if $ingressRule.servicePort }}
  {{- $svcPort = $ingressRule.servicePort -}}
  {{- else }}
  {{- $svcPort = (index $.Values.service.ports 0).port -}}
  {{- end }}

  {{- $svcName := "" }}
  {{- if $ingressRule.serviceName }}
  {{- $svcName = $ingressRule.serviceName -}}
  {{- else }}
  {{- if $.Values.service.name }}
  {{- $svcName = $.Values.service.name -}}
  {{- else }}
  {{- $svcName = $.Release.Name -}}
  {{- end }}
  {{- end }}
  - host: {{ $ingressRule.host | quote }}
    http:
      paths:
      - backend:
        {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"}}
          service:
            name: {{ $svcName | quote }}
            port:
              number: {{ $svcPort }}
        {{- else }}
          serviceName: {{ $svcName }}
          servicePort: {{ $svcPort }}
        {{- end }}
        {{- if $ingressRule.path }}
        path: {{ $ingressRule.path | quote }}
        {{- else }}
        path: /
        {{- end }}
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.Version }}
        {{- if $ingressRule.pathType }}
        pathType: {{ $ingressRule.pathType | quote }}
        {{- else }}
        pathType: ImplementationSpecific
        {{- end }}
        {{- end }}
        
  {{- end }}
  {{- if ne (printf "%s" $tlsSecretName) "" }}
  tls:
  - hosts:
    {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}
    - {{ $ingressRule.host | quote }}
    {{- end }}
    secretName: {{ $tlsSecretName | quote }}
  {{- end }}

---

{{- end }}
{{- end }}
