{{- range $portMapIndex, $portMapUnused := $.Values.service.ports }}
{{- if eq $portMapIndex 0 }}
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.service.name }}
  name: {{ $.Values.service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.service.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.service.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  externalIPs:
    {{- range $externalIPIndex, $externalIP := $.Values.service.externalIPs }}
    - {{ $externalIP }}
    {{- end }}
  ports:
    {{- range $portMapIndex, $portMap := $.Values.service.ports }}
    {{- if $portMap.name }}
    - name: {{ $portMap.name }}
    {{- else }}
    - name: "port-{{ $portMapIndex }}"
    {{- end }}
      port: {{ $portMap.port }}
      {{- if $portMap.containerPort }}
      targetPort: {{ $portMap.containerPort }}
      {{- else }}
      targetPort: {{ $portMap.port }}
      {{- end }}
      protocol: {{ $portMap.protocol | default "TCP" | quote }}
    {{- end }}
  selector:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
  type: {{ $.Values.service.type | default "ClusterIP" | quote }}
{{- end }}
{{- end }}